### ISSUE TITLE
Searching by keyword kiwiki doesnt return any results

### ISSUE THREAD

**Issue by Matet17** [aleon1220/kiwiki#2]
## Intro
Change of name required=is hard to find the name of this project.

## Direct Request
Could you change the name of the repo for Kiwiki? 

Thank you

**Comment by aleon1220** [comment]
i acknowledge this request. I will execute the change. Thanks for pointing it out @Matet17 
Bless you

**Comment by aleon1220** [comment]
Done. Closing issue.
